Feat/hyunbin - [여러분의 코멘트가 필요합니다!!!]
LM-channel-team-project/WantoDo pull request #166
Opened 2021-05-09 15:21 UTC by hyunbin1

[WantoDo - 단 하나의 일정 관리 - Chrome 2021-05-10 00-16-27.zip](https://github.com/LM-channel-team-project/WantoDo/files/6447796/WantoDo.-.-.Chrome.2021-05-10.00-16-27.zip)

파일크기가 너무 커서 압축파일로 올립니다 ㅠㅠ

Problem!!!!
1. 켈린더 아이콘 스타일 속성을 교체하고 싶은데 component 에서 캘린더 아이콘이 어딨는지 모르겠습니다 ㅠㅠ 그래서 아직 styleName=""을 어디에 넣어야될지 모르겠습니다 ㅠㅠㅠㅠ 아시는분 손!!✋✋✋

2. 제가 똥손이라 스타일을 했지만 별로일수도 있을거 같습니다!! 모두 스타일 지적 한번씩 다 해고 가주세요!!

2021-05-10 00:12 UTC, castleMo commented
디자인적인거는 저도잘몰라서 다른분들에게 토스!

모달창이 너무 큰거같은대 기분탓일까요?

2021-05-10 00:21 UTC, hyunbin1 commented
> 디자인적인거는 저도잘몰라서 다른분들에게 토스!
> 
> 모달창이 너무 큰거같은대 기분탓일까요?

아 제가 동영상찍으려구 확대해놓아서 그렇습니당 ㅎㅎ

2021-05-10 00:40 UTC, hyunbin1 commented
[100%일때]
![image](https://user-images.githubusercontent.com/63040492/117592445-86737100-b173-11eb-8526-f82adf8a8a7a.png)

[110%일때]
![image](https://user-images.githubusercontent.com/63040492/117592479-a3a83f80-b173-11eb-8cdd-fa52b5cc9f1f.png)

[125%일때]
![image](https://user-images.githubusercontent.com/63040492/117592493-b28ef200-b173-11eb-899d-0f9e83dd972d.png)

[150%일때]
![image](https://user-images.githubusercontent.com/63040492/117592520-ca667600-b173-11eb-8825-b53f5fb11420.png)

2021-05-10 00:42 UTC, hyunbin1 commented
흠 성모님 말씀듣고 다시 봤더니 조금 큰거같내용!! 아마 이렇게 보면 보기 힘드실거같지만..!

2021-05-10 01:07 UTC, castleMo commented
저렇게 보니 크기 나쁘지않은거같아요!

2021-05-10 11:49 UTC, hae-on commented
현빈님 아까 말한 거 고쳐지면 다시 캡쳐해서 올려주세유~~ 😛😛😛

2021-05-10 12:07 UTC, youngrongoh commented on front/src/styles/TaskForm.module.css
> +}
파일 내용이 끝나면 맨 끝에는 개행문자(엔터 한 번 꾹!)를 추가해주시는게 좋아요😊
자세한 이유는 노션에 정리한 내용을 참고 해주세요~
https://www.notion.so/No-newline-at-end-of-file-762921b730f74b2b8f8a04d436e03e12

2021-05-10 12:17 UTC, youngrongoh commented on front/src/styles/TaskForm.module.css
> -}
바로 앞에 커밋과 이름이 겹치네요..!😱
수정 사항을 예상할 수 있는 커밋 제목을 입력해주시면 더 좋을 것 같아요😊

2021-05-10 12:17 UTC, youngrongoh commented on front/src/components/PrioritySelector.jsx
> -      {}
혹시 이 부분 지우셨을 때 에러메시지 안 나오셨나요??

2021-05-10 12:17 UTC, youngrongoh commented on front/src/styles/InputBox.module.css
> -/* afterText 클레스네임은 어딨죠,,, */
![InputBox](https://user-images.githubusercontent.com/64844815/117657652-c6b70b80-b1d4-11eb-909c-e9a53047cad8.png)
`.text`를 사용하시면 돼요!😊

2021-05-10 12:17 UTC, youngrongoh commented on front/src/styles/InputBox.module.css
> +  margin-right:1px;
커밋 제목에서 어떤 부분을 변경하셨는지 혹은 변경하신 이유를 간단히,
제목에서 30자가 넘어갈 정도라면, 본문에 작성해주시면 좋을 것 같습니다😭

2021-05-10 12:28 UTC, hyunbin1 commented on front/src/styles/TaskForm.module.css
> +}
아하! 확인했습니당 ㅎㅎ

2021-05-10 12:29 UTC, hyunbin1 commented
> 현빈님 아까 말한 거 고쳐지면 다시 캡쳐해서 올려주세유~~ 😛😛😛

넹!!

2021-05-10 12:32 UTC, hyunbin1 commented on front/src/styles/InputBox.module.css
> -/* afterText 클레스네임은 어딨죠,,, */
아하 그렇게 하겠습니다! Aftertext는 이상하게도 .text 로 사용하면 적용이 안되고.name을 써야 실행이 되더라구여..! 혹시 왜그런지 알수있을까용??

2021-05-10 12:32 UTC, hyunbin1 commented on front/src/styles/InputBox.module.css
> +  margin-right:1px;
하핫 커밋 메세지 디테일하게 쓰겠습니당..!

2021-05-10 16:06 UTC, youngrongoh requested changes
`yarn.lock`과 `packge-lock.json`은 임의로 수정하시면 안됩니다 ㅠㅠㅠㅠㅠㅠ
yarn과 npm이 알아서 해주는 부분이에요ㅠㅠ

2021-05-11 02:29 UTC, hyunbin1 reviewed
> 제목이 너무 길어요😭
> 상세 내용은 본문으로 넣어주세요~
> 
> 현재 [Fix] 머릿말은 버그 수정용으로 사용하고 있어요
> 새로 추가된 기능과 관련된 PR에 대한 수정 사항은 이전에 있던 내용이 아니므로
> [Add]를 써주시는게 맞는거 같아요..!
> 
> 근데 이게 좀 애매하긴 해서 이 부분은 회의 때 얘기해봐도 좋을 것 같네요!
> 
> 커밋 메시지 작성하실 때,
> 
> ```
> 제목 쓰고
>  <-----(한줄 공백 쓰고)
> - 본문을 쓰시면 됩니다
> - 본문에 작성할 사항이 여러 가지인 경우에는 '-'를 앞에 붙여 구분해주세요.
> ```
> 
> 커밋하실 때 `git commit -m` or `-am` 이런 속성 쓰시지 말고 `git commit` 바로 실행해주세요.
> 그러면 커밋을 어떻게 작성해야 하는지에 대한 템플릿이 나와요!
> 자세한 내용은 그 템플릿을 참고해주세요~

아하 이렇게 하는거균여!!! 본문을 깃헙에서 뜨게하는줄알았는데 안되더라구여 ㅋㅋㅋㅋㅋㅋㅋ!!

2021-05-11 02:29 UTC, hyunbin1 commented on front/src/styles/InputBox.module.css
> -/* afterText 클레스네임은 어딨죠,,, */
넹! 저거랑 똑같아요!!

2021-05-11 02:54 UTC, hyunbin1 commented on front/yarn.lock
> +  version "1.14.1"
이부분은 develop에 이미 있는 부분입니다!

2021-05-11 04:24 UTC, youngrongoh commented on front/src/styles/InputBox.module.css
> -/* afterText 클레스네임은 어딨죠,,, */
저는 잘 나오는데 이상하네요..
![테스트](https://user-images.githubusercontent.com/64844815/117757682-7fc02900-b25b-11eb-9dcf-1346def678ca.png)
![css](https://user-images.githubusercontent.com/64844815/117758041-391efe80-b25c-11eb-9099-ac7a3c66c5cd.png)

2021-05-11 04:26 UTC, youngrongoh commented on front/yarn.lock
> +  version "1.14.1"
네 그래서 새로 커밋을 올리실게 아니라 해당 커밋에 반영된 변경사항을 바꾸셔야 할거 같아요..!

2021-05-11 09:09 UTC, hyunbin1 commented on front/yarn.lock
> +  version "1.14.1"
이부분도 충돌나서 저부분으로 바꾼건데 이거말고 다른방법도 있나요?

2021-05-12 01:55 UTC, youngrongoh commented on front/yarn.lock
> +  version "1.14.1"
패키지를 추가하거나 삭제한게 아닌데 yarn.lock 같은 파일에서 왜 충돌이 나는지는 모르겠어요..

그리고 저렇게 프로젝트 세팅과 관련된 부분은 충돌이 생겨도 원격저장소의 내용을 따라 주시면 됩니다😊

혹시나 수정 하셨더라도 커밋 하실 때 해당 파일을 포함시키지 않으시면 돼요!

저도 개발하면서 테스트 하느라 콘솔 찍고, 선언 해놓은 변수를 잠깐 사용 안하도록 해놓으면 eslint에서 오류 뱉는데 그게 불편해서 설정 변경해서 쓰고 있어요.
대신 커밋할 때는 그 설정 파일은 안 올리고요!

그렇기 때문에 커밋하실 때 어떤 파일을 포함시켜야 할지, 커밋 제목 & 내용과 관련 없는 파일은 없는지 항상 체크해주시는게 좋아요!

코드 리뷰에 대한 수정들은 [rebase](https://nochoco-lee.tistory.com/122?category=343045)를 참고해주세요.를 이용하시면 됩니다.
rebase를 통해 커밋을 분리할 것들은 분리하고, 지울 것들은 지우시고
-> 원격 브랜치(origin/feat/hyunbin)를 지우신 다음
-> 로컬 브랜치를 다시 원격으로 push하시면
변경된 사항이 적용된 브랜치가 원격에 올라올거에요.
그럼 다시 PR을 올리시면 됩니다!

2021-05-12 13:12 UTC, closed without merging