[Add] : 퀵버튼 추가
LM-channel-team-project/WantoDo pull request #44
Opened 2021-04-19 00:35 UTC by 2-seungjin

[Add] : 퀵버튼 추가

2021-04-19 03:21 UTC, youngrongoh requested changes
고생하셨습니다😊
두 가지 사항만 확인해주시면 좋을 것 같아요..!

2021-04-19 03:21 UTC, youngrongoh commented on front/src/components/QuickButton.jsx
> +    };
우리가 _styled-component_ 같은 라이브러리를 쓰지 않아서 스타일링은 css에 모아 놓으면 좋을 것 같아요😊
`src/styles/QuickButton.module.css` 파일을 만들어 주시면 솔비님이 해주실 거에요!ㅎㅎ
기본적인 스타일링을 해야하는 상황이라면 `.module.css` 파일에서 해주시면 될 것 같습니다~

2021-04-19 03:21 UTC, youngrongoh commented on front/src/components/QuickButton.jsx
> +        </div>
`src/components/IconButton.jsx`를 재사용 해주시면 좋을 것 같습니다🤗

2021-04-22 12:32 UTC, 2-seungjin commented on front/src/components/QuickButton.jsx
> +    };
네 조치 하겠습니다

2021-04-24 02:23 UTC, youngrongoh approved these changes
고생하셨습니다~😊

2021-04-24 02:23 UTC, merged